In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
voc_size=10000

In [25]:
### One Hot Representation 
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3830, 3684, 9039, 3811],
 [3830, 3684, 9039, 392],
 [3830, 7268, 9039, 5071],
 [8911, 2364, 7179, 6090, 6305],
 [8911, 2364, 7179, 6090, 5590],
 [1917, 3830, 6457, 9039, 961],
 [5071, 3789, 3035, 6090]]

In [26]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3830 3684 9039 3811]
 [   0    0    0    0 3830 3684 9039  392]
 [   0    0    0    0 3830 7268 9039 5071]
 [   0    0    0 8911 2364 7179 6090 6305]
 [   0    0    0 8911 2364 7179 6090 5590]
 [   0    0    0 1917 3830 6457 9039  961]
 [   0    0    0    0 5071 3789 3035 6090]]


In [28]:
## feature representation
dim=10

In [29]:
# Embedding layer
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[[ 0.04691562, -0.04600964,  0.00442285,  0.04820672,
          0.04763864, -0.00788424,  0.02806019, -0.03319998,
          0.03374553,  0.04692055],
        [ 0.04691562, -0.04600964,  0.00442285,  0.04820672,
          0.04763864, -0.00788424,  0.02806019, -0.03319998,
          0.03374553,  0.04692055],
        [ 0.04691562, -0.04600964,  0.00442285,  0.04820672,
          0.04763864, -0.00788424,  0.02806019, -0.03319998,
          0.03374553,  0.04692055],
        [ 0.04691562, -0.04600964,  0.00442285,  0.04820672,
          0.04763864, -0.00788424,  0.02806019, -0.03319998,
          0.03374553,  0.04692055],
        [ 0.03076552,  0.04387638, -0.02466186,  0.03084872,
          0.03732573,  0.04849492,  0.04683897, -0.00689299,
         -0.01783277,  0.00522243],
        [ 0.04315938,  0.02974763, -0.04776701, -0.04471225,
         -0.00409107,  0.04948454, -0.0149744 ,  0.02305366,
         -0.03258418, -0.04515634],
        [-0.04000391,  0.02247145, -0.02824733,  0.0

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 3830, 3684, 9039, 3811], dtype=int32)

In [46]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[ 0.04691562, -0.04600964,  0.00442285,  0.04820672,  0.04763864,
        -0.00788424,  0.02806019, -0.03319998,  0.03374553,  0.04692055],
       [ 0.04691562, -0.04600964,  0.00442285,  0.04820672,  0.04763864,
        -0.00788424,  0.02806019, -0.03319998,  0.03374553,  0.04692055],
       [ 0.04691562, -0.04600964,  0.00442285,  0.04820672,  0.04763864,
        -0.00788424,  0.02806019, -0.03319998,  0.03374553,  0.04692055],
       [ 0.04691562, -0.04600964,  0.00442285,  0.04820672,  0.04763864,
        -0.00788424,  0.02806019, -0.03319998,  0.03374553,  0.04692055],
       [ 0.03076552,  0.04387638, -0.02466186,  0.03084872,  0.03732573,
         0.04849492,  0.04683897, -0.00689299, -0.01783277,  0.00522243],
       [ 0.04315938,  0.02974763, -0.04776701, -0.04471225, -0.00409107,
         0.04948454, -0.0149744 ,  0.02305366, -0.03258418, -0.04515634],
       [-0.04000391,  0.02247145, -0.02824733,  0.03669626, -0.03422331,
        -0.02464131,  0.03902659, -0.00151207